# Generated by Django 3.2 on 2023-02-26 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wine_tasting', '0002_experiences_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookin_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('booking_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Confirmed'), (0, 'Not Confirmed')], default=0)),
                ('experience_choice', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, related_name='experience_list', to='wine_tasting.experiences')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
    ]
