# Generated by Django 3.2 on 2023-02-26 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bookin_id',
            new_name='booking_id',
        ),
    ]
