# Generated by Django 3.2 on 2023-02-28 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wine_tasting', '0002_experiences_image_url'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_ref',
            field=models.CharField(default='', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people', models.IntegerField(default=1)),
                ('bookingitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('bookings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingitem', to='booking.booking')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine_tasting.experiences')),
            ],
        ),
    ]
