# Generated by Django 3.2 on 2023-02-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_bookin_id_booking_booking_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_id',
            new_name='booking_ref',
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_people',
            field=models.IntegerField(default=1),
        ),
    ]
