# Generated by Django 3.2 on 2023-05-09 17:35

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20230305_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, null=True, validators=[booking.models.validate_date]),
        ),
    ]
