# Generated by Django 3.2 on 2023-07-28 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wine_tasting', '0003_alter_experiences_image'),
        ('products', '0004_remove_product_user_wishlist'),
        ('checkout', '0005_orderlineitem_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wine_tasting.experiences'),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
