# Generated by Django 3.2 on 2023-08-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20230728_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_booking',
            field=models.TextField(default=''),
        ),
    ]
