# Generated by Django 3.2 on 2023-08-18 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_order_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='experience',
        ),
    ]
