# Generated by Django 3.2 on 2023-05-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_tasting', '0002_experiences_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
