# Generated by Django 3.2 on 2023-07-18 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_user_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user_wishlist',
        ),
    ]
